apiVersion: v2
name: opensearch-kafka-connector
description: OpenSearch Kafka Connector Helm chart
type: application
version: 0.0.0-develop
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenSearch Kafka Connector"
