{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" .Subcharts.opensearch }}-custom-config
  labels: {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.opensearch.security.enabled }}
  {{- if .Values.opensearch.security.extraConfig }}
  opensearch-security-config.yml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.opensearch.security.extraConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.opensearch.dashboards.enabled }}
  {{- if .Values.opensearch.dashboards.extraConfig }}
  opensearch_dashboards.yml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.opensearch.dashboards.extraConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
